# Generated by Django 5.2.5 on 2025-08-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("createdon", models.DateTimeField(auto_now_add=True)),
                ("file", models.FileField(blank=True, null=True, upload_to="")),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
            ],
        ),
    ]
