# Generated by Django 5.2.5 on 2025-09-08 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="announcement",
            old_name="type",
            new_name="types",
        ),
    ]
