# Generated by Django 5.2.5 on 2025-09-09 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_announcement_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="announcement",
            name="image",
        ),
        migrations.AlterField(
            model_name="announcement",
            name="types",
            field=models.CharField(
                blank=True,
                choices=[
                    ("events", "events"),
                    ("final exam", "final exam"),
                    ("mst", "mst"),
                    ("warning", "warning"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
