# Generated by Django 5.2.5 on 2025-09-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_remove_announcement_image_alter_announcement_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="announcement image/"
            ),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="title",
            field=models.CharField(max_length=500),
        ),
    ]
