# Generated by Django 5.2.5 on 2025-09-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="posts",
            field=models.FileField(blank=True, null=True, upload_to="posts/"),
        ),
    ]
