# Generated by Django 5.2.5 on 2025-09-06 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0003_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="likes",
            name="post",
        ),
        migrations.RemoveField(
            model_name="likes",
            name="user",
        ),
        migrations.DeleteModel(
            name="comment",
        ),
        migrations.DeleteModel(
            name="likes",
        ),
    ]
