# Generated by Django 5.2.5 on 2025-09-12 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assigment",
            name="last_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
