# Generated by Django 5.2.5 on 2025-09-12 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignment", "0002_assigment_last_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assigment",
            name="sumbite_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
