# Generated by Django 5.2.5 on 2025-09-16 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assignment", "0003_alter_assigment_sumbite_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assigment",
            name="sumbite_date",
        ),
    ]
