# Generated by Django 5.2.5 on 2025-09-07 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0003_initial"),
        ("users", "0002_alter_user_bio_alter_user_branch_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_post",
                to="post.post",
            ),
        ),
    ]
