# Generated by Django 5.2.5 on 2025-09-07 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_user_post"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="user_post",
        ),
    ]
