# Generated by Django 5.2.5 on 2025-09-09 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_user_user_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[("student", "Student"), ("faculty", "Faculty")],
                max_length=10,
                null=True,
            ),
        ),
    ]
